// For demonstration purposes, let's use a static list of suggestions
export const staticSuggestions = [
  'Lagos, Nigeria',
  'Abuja, Nigeria',
  'New York, USA',
  'Tokyo, Japan',
  'London, UK',
  'Paris, France',
  'Berlin, Germany',
  'Sydney, Australia',
  'Beijing, China',
  'Mumbai, India',
  'Cairo, Egypt',
  'Cape Town, South Africa',
  'Moscow, Russia',
  'Rio de Janeiro, Brazil',
  'Toronto, Canada',
  'Mexico City, Mexico',
  'Dubai, UAE',
  'Seoul, South Korea',
  'Hanoi, Vietnam',
  'Bangkok, Thailand',
  'Singapore',
  'Rome, Italy',
  'Barcelona, Spain',
  'Athens, Greece',
  'Istanbul, Turkey',
  'Nairobi, Kenya',
  'Buenos Aires, Argentina',
  'Lima, Peru',
  'Auckland, New Zealand',
  'Stockholm, Sweden',
  'Oslo, Norway',
  'Copenhagen, Denmark',
  'Helsinki, Finland',
  'Amsterdam, Netherlands',
  'Brussels, Belgium',
  'Vienna, Austria',
  'Zurich, Switzerland',
  'Dublin, Ireland',
  'Warsaw, Poland',
  'Prague, Czech Republic',
  'Budapest, Hungary',
  'Lisbon, Portugal',
  'Madrid, Spain',
  'Edinburgh, Scotland',
  'Cardiff, Wales',
  'Belfast, Northern Ireland',
  'Ankara, Turkey',
  'Jerusalem, Israel',
  'Copenhagen, Denmark',
  'Stockholm, Sweden',
  'Oslo, Norway',
  'Helsinki, Finland',
  'Amsterdam, Netherlands',
  'Brussels, Belgium',
  'Vienna, Austria',
  'Zurich, Switzerland',
  'Dublin, Ireland',
  'Warsaw, Poland',
  'Prague, Czech Republic',
  'Budapest, Hungary',
  'Lisbon, Portugal',
  'Madrid, Spain',
  'Edinburgh, Scotland',
  'Cardiff, Wales',
  'Belfast, Northern Ireland',
  'Ankara, Turkey',
  'Jerusalem, Israel',
  'Ado-Ekiti, Nigeria',
  'Ilorin, Nigeria',
  'Offa, Nigeria',
  // Add more as neede
];
