#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
 
echo 'Evento File Checks'
echo '' 
echo '🏗️👷 Styling your project before committing👷‍♂️🏗️'
echo ''
echo 'please be patient, this may take a while...'
 
# Check ESLint Standards
npm run lint ||
(
    echo '🔨❌ Yoo, you have a problem in your code. Check linter 🔨❌
          Run npm run lint, add changes and try commit again.';
    false;
)
 
echo '🎉 No error found: committing this now.... ✨🚀🏄‍♂️🍻'
 
npm run lint-staged